language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: QxYerRayRCVTAE/cnH1qZBpTpA/QtHrU09oHqxA4d+OFp33ieYltvaSRNYRLqUncVRabeRrwEbzpMLGkoBlZdHIHPwHA/S7VjzFJxJihhJ2yWyNLSDAIOt4bQ3wQpRRlyZuwWuwWiMO3g9jKoMzgwSJqnwR9W4/xBJcVMIxf2DgP6qF4CkqCrnplFRi5cvg/4TZUEuU0eiFI7R1X+H4VXFGJFJjbo0fjrhG2OMJqtf46VyMEFYiVtNnU2Bgho+wltEci3uX0A0FUO6A5RlBFn2J8ZhdynHkJVIQV63eVecXbI5XJq2DzhEAqD78Evn6lloFneILkuF5OXWCBpjmWGeqMzwMEnEcK41MWn1XvDq5WYdzama1dEQKsBMCR7LPz9LHQRpcZDVTC/B6RblUh7sWSJPQWTrCTCZ8z1wkPi0wILGyVVLt34BN9/gq4mzaKlOgfLZCiWJkjdA3MHof5OkBUPklZ2Jjz5K4UnuiSMgmjPcX7RX++xmdgJ6eA1chQ15qrmw/5Sy00Kd38k0k5dALccRkfAqH6UpHIXIQCLd14piHYeBqZYmZkOJbu0kIzeNK9ZZzJuxo/et1Tco4Ax9yU+WUc2fsYA8yyG3HlJ+cjRO/dUFu3D9/38nr+F51tXLaUZyKEEGZliKa6P752+nqKxUqe8J8xXwAKvl7MmqM=
